#!/usr/bin/env python3
"""Generate and check the casegraphen-operate consumer contract."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SKILL = ROOT / "skills/casegraphen-operate"
USAGE = ROOT / "src/cli_usage.txt"
REPORT_SCHEMA = ROOT / "schemas/casegraphen/native-cli.report.schema.json"
GENERATED = SKILL / "capabilities.generated.md"
REPORTING_SOURCE = ROOT / "src/native_cli_reporting.rs"
ERROR_SOURCES = (ROOT / "src/native_cli.rs", ROOT / "src/native_store/types.rs")
OBSOLETE = (
    "There is no fan-out.",
    "every revision writes a full snapshot",
    "One invocation advances at most one step.",
)


def usage_rows() -> list[tuple[str, tuple[str, ...]]]:
    rows: list[tuple[str, tuple[str, ...]]] = []
    for raw in USAGE.read_text().splitlines():
        line = raw.strip()
        if not line.startswith("casegraphen "):
            continue
        signature = line.split("  (", 1)[0]
        tokens = signature.split()
        path: list[str] = []
        for token in tokens[1:]:
            if token.startswith(("<", "[", "(")):
                break
            if token.startswith("--"):
                if not path and token == "--version":
                    path.append(token)
                    continue
                if path == ["run"] and token in ("--step", "--frontier"):
                    path.append(token)
                    continue
                break
            path.append(token)
        flags = tuple(sorted(set(re.findall(r"--[a-z][a-z0-9-]*", signature))))
        alternatives = [part.split("|") for part in path]
        expanded = [[]]
        for choices in alternatives:
            expanded = [base + [choice] for base in expanded for choice in choices]
        for command in expanded:
            rows.append((" ".join(command), flags))
    return sorted(set(rows))


def rust_match_strings(source: str, function: str) -> list[str]:
    marker = f"fn {function}(&self)"
    start = source.index(marker)
    body_start = source.index("{", start)
    depth = 0
    for index in range(body_start, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                body = source[body_start:index]
                return re.findall(r'"([a-z][a-z0-9_]*)"', body)
    raise ValueError(f"unterminated {function} in Rust source")


def schema_vocabularies() -> tuple[list[str], list[str], list[str]]:
    report = json.loads(REPORT_SCHEMA.read_text())
    halts = report["$defs"]["halt_report"]["properties"]["halt"]["enum"]
    reporting = REPORTING_SOURCE.read_text()
    status_body = reporting.split("pub(crate) const OPERATION_STATUSES", 1)[1].split("];", 1)[0]
    statuses = re.findall(r'"([a-z][a-z0-9_]*)"', status_body)
    errors: set[str] = set()
    for source_path in ERROR_SOURCES:
        errors.update(rust_match_strings(source_path.read_text(), "error_code"))
    return sorted(statuses), sorted(halts), sorted(errors)


def render() -> str:
    statuses, halts, errors = schema_vocabularies()
    lines = [
        "# casegraphen-operate capability surface",
        "",
        "<!-- Generated by scripts/skill-conformance.py; do not edit. -->",
        "",
        "Sources: `src/cli_usage.txt`, `native-cli.report.schema.json`,",
        "`src/native_cli_reporting.rs`, `src/native_cli.rs`, and",
        "`src/native_store/types.rs`. `tests/cli_surface.rs` verifies that the usage",
        "commands and flags reach the shipped parser.",
        "",
        "## Commands and flags",
        "",
        "| Command | Accepted flags declared by the CLI |",
        "|---|---|",
    ]
    for command, flags in usage_rows():
        rendered_flags = ", ".join(f"`{flag}`" for flag in flags) or "—"
        lines.append(f"| `casegraphen {command}` | {rendered_flags} |")
    for title, values in (
        ("Operation statuses", statuses),
        ("Halt reasons", halts),
        ("Known local refusal codes", errors),
    ):
        lines.extend(
            ["", f"## {title}", "", ", ".join(f"`{value}`" for value in sorted(values))]
        )
    lines.append("")
    return "\n".join(lines)


def line_error(path: pathlib.Path, line: int, message: str) -> str:
    try:
        display = path.resolve().relative_to(ROOT)
    except ValueError:
        display = path
    return f"{display}:{line}: {message}"


def validate_document(path: pathlib.Path) -> list[str]:
    text = path.read_text()
    errors: list[str] = []
    command_flags = {command: set(flags) for command, flags in usage_rows()}
    all_flags = set().union(*command_flags.values())
    operation_statuses, halts, refusal_codes = schema_vocabularies()
    statuses = set(operation_statuses)

    for obsolete in OBSOLETE:
        for match in re.finditer(re.escape(obsolete), text, re.IGNORECASE):
            errors.append(
                line_error(
                    path,
                    text.count("\n", 0, match.start()) + 1,
                    f"obsolete claim: {obsolete!r}",
                )
            )

    for match in re.finditer(r"`(--[a-z][a-z0-9-]*)[^`]*`", text):
        flag = match.group(1)
        if flag not in all_flags:
            errors.append(
                line_error(
                    path,
                    text.count("\n", 0, match.start()) + 1,
                    f"unknown CLI flag {flag!r}",
                )
            )

    in_shell_fence = False
    pending_command = ""
    pending_line = 0
    in_error_taxonomy = False

    def validate_command(fragment: str, line_number: int) -> None:
        tokens = re.findall(r"--[a-z][a-z0-9-]*|[a-z][a-z0-9-]*", fragment)
        if not tokens or tokens[0] != "casegraphen":
            return
        words = tokens[1:]
        candidates = [
            command
            for command in command_flags
            if words[: len(command.split())] == command.split()
        ]
        if not candidates:
            errors.append(
                line_error(path, line_number, f"unknown command in {fragment.strip()!r}")
            )
            return
        command = max(candidates, key=lambda item: len(item.split()))
        for flag in (
            token for token in words[len(command.split()) :] if token.startswith("--")
        ):
            if flag not in command_flags[command]:
                errors.append(
                    line_error(
                        path,
                        line_number,
                        f"flag {flag!r} is not accepted by `casegraphen {command}`",
                    )
                )

    for line_number, line in enumerate(text.splitlines(), 1):
        if "`error_code` also distinguishes" in line:
            in_error_taxonomy = True
        elif in_error_taxonomy and line.startswith("**A refusal can carry"):
            in_error_taxonomy = False
        if in_error_taxonomy:
            error_name = re.match(r'^\s*-\s+`"?([a-z][a-z0-9_]*)"?`', line)
            if error_name and error_name.group(1) not in refusal_codes:
                errors.append(
                    line_error(
                        path,
                        line_number,
                        f"unknown refusal code {error_name.group(1)!r}",
                    )
                )
        for match in re.finditer(r"(?<![a-z_])status:\s*`?([a-z][a-z0-9_]*)", line):
            value = match.group(1)
            if value not in statuses:
                errors.append(
                    line_error(path, line_number, f"unknown operation status {value!r}")
                )
        for match in re.finditer(r"halt:\s*`?([a-z][a-z0-9_]*)", line):
            value = match.group(1)
            if value not in halts:
                errors.append(line_error(path, line_number, f"unknown halt reason {value!r}"))
        stripped = line.strip()
        if stripped.startswith("```"):
            if in_shell_fence and pending_command:
                validate_command(pending_command, pending_line)
                pending_command = ""
            in_shell_fence = stripped in ("```sh", "```shell", "```bash")
            continue
        if not in_shell_fence:
            continue
        code = line.split("#", 1)[0].strip()
        if not pending_command and "casegraphen " not in code:
            continue
        if not pending_command:
            pending_line = line_number
            code = code[code.index("casegraphen ") :]
        continued = code.endswith("\\")
        command_part = code[:-1].strip() if continued else code
        pending_command = f"{pending_command} {command_part}".strip()
        if not continued:
            validate_command(pending_command, pending_line)
            pending_command = ""
    return errors


def check() -> list[str]:
    errors: list[str] = []
    expected = render()
    actual = GENERATED.read_text() if GENERATED.exists() else ""
    if actual != expected:
        errors.append(
            f"{GENERATED.relative_to(ROOT)}: generated surface is stale; "
            "run `python3 scripts/skill-conformance.py --write`"
        )
    for path in sorted(SKILL.rglob("*.md")):
        if path != GENERATED:
            errors.extend(validate_document(path))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--check", action="store_true")
    action.add_argument("--check-document", type=pathlib.Path)
    args = parser.parse_args()
    if args.write:
        GENERATED.write_text(render())
        print(f"wrote {GENERATED.relative_to(ROOT)}")
        return 0
    errors = validate_document(args.check_document) if args.check_document else check()
    if errors:
        print("\n".join(f"FAIL {error}" for error in errors), file=sys.stderr)
        return 1
    print("ok: casegraphen-operate matches the shipped CLI and schema surface")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
